using System.Threading.Tasks;
using System.Text.RegularExpressions;
using Microsoft.Playwright;
using System;

using var playwright = await Playwright.CreateAsync();
await using var browser = await playwright.Chromium.LaunchAsync(new()
{
    Headless = false,
});
var context = await browser.NewContextAsync();

var page = await context.NewPageAsync();
page.SetDefaultTimeout(200000);
page.SetDefaultNavigationTimeout(200000); // for some reason match loading is slow

await page.GotoAsync("http://localhost:5136/");
await page.GetByText("Pokémon Project").ClickAsync();
await page.GetByText("Search Pokémon").ClickAsync();
await page.GetByText("Find Your Pokémon Twin").ClickAsync();
await page.GetByRole(AriaRole.Article).GetByText("Top Pokémon").ClickAsync();
await page.GetByRole(AriaRole.Link, new() { Name = "Discover" }).ClickAsync();
await page.GetByRole(AriaRole.Heading, new() { Name = "Top 10 Pokémon" }).ClickAsync();
await page.GetByRole(AriaRole.Link, new() { Name = "Pokemon Project" }).ClickAsync();
await page.GetByRole(AriaRole.Link, new() { Name = "Find Match" }).ClickAsync();
await page.GetByRole(AriaRole.Heading, new() { Name = "Find Your Pokémon Twin" }).ClickAsync();
await page.GetByRole(AriaRole.Link, new() { Name = "Pokemon Project" }).ClickAsync();
await page.GetByRole(AriaRole.Link, new() { Name = "Start Searching" }).ClickAsync();
await page.GetByRole(AriaRole.Heading, new() { Name = "Pokémon Search" }).ClickAsync();
await page.GetByRole(AriaRole.Textbox, new() { Name = "Enter Pokemon name or ID..." }).ClickAsync();
await page.GetByRole(AriaRole.Textbox, new() { Name = "Enter Pokemon name or ID..." }).FillAsync("pikachu");
await page.GetByRole(AriaRole.Button, new() { Name = "Search" }).ClickAsync();
await page.GetByRole(AriaRole.Heading, new() { Name = "pikachu (25)" }).ClickAsync();
await page.GetByRole(AriaRole.Img, new() { Name = "pikachu" }).ClickAsync();
await page.GetByRole(AriaRole.Button, new() { Name = "Random" }).ClickAsync();
await page.GetByText("Height:").ClickAsync();
await page.GetByRole(AriaRole.Link, new() { Name = "Match Me" }).ClickAsync();
await page.GetByRole(AriaRole.Spinbutton).First.ClickAsync();
await page.GetByRole(AriaRole.Spinbutton).First.FillAsync("-1");
await page.GetByRole(AriaRole.Spinbutton).Nth(1).ClickAsync();
await page.GetByRole(AriaRole.Spinbutton).Nth(1).FillAsync("-1");
await page.GetByRole(AriaRole.Spinbutton).Nth(2).ClickAsync();
await page.GetByRole(AriaRole.Spinbutton).Nth(2).FillAsync("-1");
await page.GetByRole(AriaRole.List).GetByText("Feet must be between 0 and").ClickAsync();
await page.GetByRole(AriaRole.List).GetByText("Feet must be between 0 and").ClickAsync();
await page.GetByRole(AriaRole.List).GetByText("Inches must be between 0 and").ClickAsync();
await page.GetByRole(AriaRole.List).GetByText("Weight must be between 1 and").ClickAsync();
await page.Locator("div").Filter(new() { HasTextRegex = new Regex("^Feet must be between 0 and 8\\.$") }).ClickAsync();
await page.Locator("div").Filter(new() { HasTextRegex = new Regex("^Inches must be between 0 and 11\\.$") }).ClickAsync();
await page.Locator("div").Filter(new() { HasTextRegex = new Regex("^Weight must be between 1 and 1000 kg\\.$") }).ClickAsync();
await page.GetByRole(AriaRole.Spinbutton).First.ClickAsync();
await page.GetByRole(AriaRole.Spinbutton).First.FillAsync("6");
await page.GetByRole(AriaRole.Spinbutton).Nth(1).ClickAsync();
await page.GetByRole(AriaRole.Spinbutton).Nth(1).FillAsync("2");
await page.GetByRole(AriaRole.Spinbutton).Nth(2).ClickAsync();
await page.GetByRole(AriaRole.Spinbutton).Nth(2).FillAsync("80");
await page.GetByRole(AriaRole.Button, new() { Name = "Find My Pokémon" }).ClickAsync();
await page.GetByRole(AriaRole.Button, new() { Name = "Find My Pokémon" }).ClickAsync();
await page.GetByRole(AriaRole.Link, new() { Name = "dragalge" }).Nth(1).ClickAsync();
await page.GetByRole(AriaRole.Heading, new() { Name = "dragalge (691)" }).ClickAsync();
await page.GetByRole(AriaRole.Link, new() { Name = " Top Pokémon" }).ClickAsync();
await page.GetByRole(AriaRole.Spinbutton).First.ClickAsync();
await page.GetByRole(AriaRole.Spinbutton).First.FillAsync("01");
await page.GetByRole(AriaRole.Spinbutton).Nth(1).ClickAsync();
await page.GetByRole(AriaRole.Spinbutton).Nth(1).FillAsync("50");
await page.GetByRole(AriaRole.Spinbutton).Nth(2).ClickAsync();
await page.GetByRole(AriaRole.Spinbutton).Nth(2).FillAsync("60");
await page.GetByRole(AriaRole.Spinbutton).Nth(3).ClickAsync();
await page.GetByRole(AriaRole.Spinbutton).Nth(3).FillAsync("10");
await page.GetByRole(AriaRole.Button, new() { Name = "Apply Filters" }).ClickAsync();
await page.GetByRole(AriaRole.Heading, new() { Name = "alomomola" }).ClickAsync();
await page.GetByRole(AriaRole.Combobox).SelectOptionAsync(new[] { "name" });
await page.GetByRole(AriaRole.Button, new() { Name = "Apply Filters" }).ClickAsync();
await page.GetByRole(AriaRole.Heading, new() { Name = "zygarde-" }).ClickAsync();
await page.GetByRole(AriaRole.Combobox).SelectOptionAsync(new[] { "attack" });
await page.GetByRole(AriaRole.Button, new() { Name = "Apply Filters" }).ClickAsync();
await page.GetByRole(AriaRole.Heading, new() { Name = "kartana" }).ClickAsync();
await page.GetByRole(AriaRole.Combobox).SelectOptionAsync(new[] { "defense" });
await page.GetByRole(AriaRole.Button, new() { Name = "Apply Filters" }).ClickAsync();
await page.GetByRole(AriaRole.Heading, new() { Name = "stakataka" }).ClickAsync();
await page.GetByRole(AriaRole.Combobox).SelectOptionAsync(new[] { "speed" });
await page.GetByRole(AriaRole.Button, new() { Name = "Apply Filters" }).ClickAsync();
await page.GetByRole(AriaRole.Heading, new() { Name = "electrode" }).ClickAsync();
await page.GetByRole(AriaRole.Combobox).SelectOptionAsync(new[] { "weight" });
await page.GetByRole(AriaRole.Button, new() { Name = "Apply Filters" }).ClickAsync();
await page.GetByRole(AriaRole.Heading, new() { Name = "celesteela" }).ClickAsync();
await page.GetByRole(AriaRole.Combobox).SelectOptionAsync(new[] { "height" });
await page.GetByRole(AriaRole.Button, new() { Name = "Apply Filters" }).ClickAsync();
await page.GetByRole(AriaRole.Heading, new() { Name = "eternatus" }).ClickAsync();
await page.GetByRole(AriaRole.Button, new() { Name = "Descending" }).ClickAsync();
await page.GetByRole(AriaRole.Heading, new() { Name = "comfey" }).ClickAsync();
await page.GetByRole(AriaRole.Link, new() { Name = "View" }).First.ClickAsync();
await page.GetByRole(AriaRole.Heading, new() { Name = "comfey (764)" }).ClickAsync();
